### ISSUE TITLE
数据集中lbl是什么数据集？

### ISSUE THREAD

**Issue by Submarinee** [AmberHen/WHU-OPT-SAR-dataset#12]
我看到您的数据集包括optical,lbl,sar,prediction这些目录，我看到optical是四波段数据，包括RGB和近红外，请问lbl是什么？我最初的猜测lbl是近红外数据，但是好像和optical第四个波段的数据均值和方差不一致，所以不太明白。
此外非常感谢您提供的数据集，这对我的工作非常有帮助。如果您有时间可以回答一下这个疑问，不尽感激。

**Comment by AmberHen** [comment]
lbl is the groud truth (or label)

**Comment by azengtao** [comment]
> lbl is the groud truth (or label)
Hello, where is the near-infrared data set mentioned in the article?

**Comment by hayhay111111sef** [comment]
请问数据集sar的极化方式是什么，来自SAR images (sampling resolution of 5 meters) are collected by GF-3 fine strip II (FS II)
