### ISSUE TITLE
关于近红外图像数据集

### ISSUE THREAD

**Issue by azengtao** [AmberHen/WHU-OPT-SAR-dataset#14]
博主，您好：
             非常感谢您提供的遥感数据集，这是我第一个找到的遥感方面融合SAR和可见光的数据集。
             我有个问题向请教您，文中提到的近红外图像数据我在提供的连接中貌似没有找到，请问在哪里可以找到您给的红外数据集呢？
能解答我的问题，我将非常感激！

祝好

**Comment by AmberHen** [comment]
The optical image consists of four channels, of which the fourth channel is the near-infrared image. You can separate it yourself.

**Comment by azengtao** [comment]
> 
Thank you very much, it has been separated. In addition, I also encountered a problem. When I reproduced the paper, there was a code problem. Can I refer to your source code? Thank you very much!
