### ISSUE TITLE
请问数据集该如何使用？

### ISSUE THREAD

**Issue by dreamkwc** [AmberHen/WHU-OPT-SAR-dataset#2]
你好，请教一下，lbl文件夹和intro/lbl文件夹中的标签文件是同名文件，但是具体补签不一致，应该使用哪个文件夹中的文件？

**Comment by AmberHen** [comment]
你好，数据请使用whu-opt-sar/image、whu-opt-sar/sar、whu-opt-sar/lbl。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmberHen/WHU-OPT-SAR-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月13日(星期天) 晚上7:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[AmberHen/WHU-OPT-SAR-dataset] 请问数据集该如何使用？ (Issue #2)





 
你好，请教一下，lbl文件夹和intro/lbl文件夹中的标签文件是同名文件，但是具体补签不一致，应该使用哪个文件夹中的文件？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dreamkwc** [comment]
> 你好，数据请使用whu-opt-sar/image、whu-opt-sar/sar、whu-opt-sar/lbl。

好的，谢谢

**Comment by dreamkwc** [comment]
@AmberHen 你好，再请教一下，各个标签0，10，20，30，40，50，70和地物类型如何对应？各类地物对应的RGB色彩具体数值是多少？

**Comment by AmberHen** [comment]
您好。0是背景，10是耕地，20是城市，30是农村，40是水体，50是森林，60是道路，70是其他。
分别对应的RGB值是：（204，102，0），（255，0，0），（255，255，0），（0，0，255），（85，167，0），（0，255，255），（153，102，153）
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmberHen/WHU-OPT-SAR-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AmberHen/WHU-OPT-SAR-dataset] 请问数据集该如何使用？ (Issue #2)





 
@AmberHen 你好，再请教一下，各个标签0，10，20，30，40，50，70和地物类型如何对应？各类地物对应的RGB色彩具体数值是多少？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dreamkwc** [comment]
> 您好。0是背景，10是耕地，20是城市，30是农村，40是水体，50是森林，60是道路，70是其他。 分别对应的RGB值是：（204，102，0），（255，0，0），（255，255，0），（0，0，255），（85，167，0），（0，255，255），（153，102，153）

@AmberHen 我对whu-opt-sar/lbl文件夹中的标签进行统计，并没有60。你这里给出的7个RGB值如何和8类地物对应？

**Comment by AmberHen** [comment]
感谢提醒。明天会修改上传新的标签。另外，背景默认颜色是（0，0，0）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmberHen/WHU-OPT-SAR-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 晚上11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AmberHen/WHU-OPT-SAR-dataset] 请问数据集该如何使用？ (Issue #2)





  
您好。0是背景，10是耕地，20是城市，30是农村，40是水体，50是森林，60是道路，70是其他。 分别对应的RGB值是：（204，102，0），（255，0，0），（255，255，0），（0，0，255），（85，167，0），（0，255，255），（153，102，153）
  
我对whu-opt-sar/lbl文件夹中的标签进行统计，并没有60。你这里给出的7个RGB值如何和8类地物对应？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dreamkwc** [comment]
@AmberHen 好的，谢谢解答。

**Comment by AmberHen** [comment]
您好。数据集已经修改上传。有问题随时联系



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日(周二) 晚上11:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AmberHen/WHU-OPT-SAR-dataset] 请问数据集该如何使用？ (Issue #2)




 
@AmberHen 好的，谢谢解答。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AmberHen** [comment]
We have updated the result image of the data prediction to the web disk.
