### ISSUE TITLE
光学图像image，四个波段的顺序是什么？

### ISSUE THREAD

**Issue by taochx** [AmberHen/WHU-OPT-SAR-dataset#3]
你好，我下载了数据集，但是在光学图像image，四个波段的顺序是什么，我尝试了不同的波段组合方式，但是未能显示真彩色图像，另外该文件中的NH49E010015图像中间有像素缺失。

**Comment by AmberHen** [comment]
您好。波段3、2、1分别是红、绿、蓝。4是近红外。另外，NH49E010015图像中间有像素缺失是本身成像的问题，所以数据就只能这样了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmberHen/WHU-OPT-SAR-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月21日(星期一) 上午9:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[AmberHen/WHU-OPT-SAR-dataset] 光学图像image，四个波段的顺序是什么？ (Issue #3)





 
你好，我下载了数据集，但是在光学图像image，四个波段的顺序是什么，我尝试了不同的波段组合方式，但是未能显示真彩色图像，另外该文件中的NH49E010015图像中间有像素缺失。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by doriz3** [comment]
> 你好，我下载了数据集，但是在光学图像image，四个波段的顺序是什么，我尝试了不同的波段组合方式，但是未能显示真彩色图像，另外该文件中的NH49E010015图像中间有像素缺失。

您好，请问您还原出彩色图像了吗？这个该怎么还原呢？

**Comment by AmberHen** [comment]
We have updated the result image of the data prediction to the web disk.
