### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by 739675943** [AmberHen/WHU-OPT-SAR-dataset#5]
您好，我对您的工作非常感兴趣，我初步了解SAR和光学图像的地物分类，不知道您能否提供论文中的带地理坐标的湖北省的遥感影像及标签和源代码以供学习呢？ 仅限个人学习使用。如果方便的话，[hukang0604@163.com] ，期待您的回复。

**Comment by AmberHen** [comment]
带坐标的图像不方便提供

**Comment by AmberHen** [comment]
We have updated the result image of the data prediction to the web disk.
