### ISSUE TITLE
optical图片色彩缺失

### ISSUE THREAD

**Issue by Zhoumoz** [AmberHen/WHU-OPT-SAR-dataset#8]
作者你好，非常感谢你分享这些有用的数据，只是我下载则optical图片色彩缺失严重，请问，下载后的optical图片应该如何进一步处理，谢谢。

**Comment by AmberHen** [comment]
能附上你认为色彩缺失的图片是什么样吗

**Comment by Zhoumoz** [comment]
![图片](https://user-images.githubusercontent.com/103343187/197473519-8fc46e2b-a2ec-4b1c-9b91-4ae64fc64923.png)

**Comment by Zhoumoz** [comment]
在optical文件夹里文件，看起来都像这样

**Comment by AmberHen** [comment]
这不是色彩缺失，这是四个通道，RGB和近红外。

**Comment by Zhoumoz** [comment]
好的

**Comment by AmberHen** [comment]
We have updated the result image of the data prediction to the web disk.
