### ISSUE TITLE
光学数据

### ISSUE THREAD

**Issue by XiaoxxWang** [AmberHen/WHU-OPT-SAR-dataset#9]
您好，感谢您分享的数据集。我对您百度云链接中的光学数据有一点疑问，我发现所有光学图像都有网格状的马赛克，和您论文中的图像看上去不太一致，是什么问题导致的呢？

**Comment by AmberHen** [comment]
因为光学是4个通道啊

**Comment by AmberHen** [comment]
We have updated the result image of the data prediction to the web disk.
